import Marty from 'marty';

export default Marty.createConstants([
    'RECEIVE_MAIL_RESEND_SUCCESS',
    'RECEIVE_MAIL_RESEND_FAILED',
    'RECEIVE_MAIL_VERIF_SUCCESS',
    'RECEIVE_MAIL_VERIF_FAILED',
    ,'RECEIVE_REGIST_SUCCESS'
    ,'RECEIVE_REGIST_FAILED'
]);
